### ISSUE TITLE
More info in test output (duration, test command line)

### ISSUE THREAD

**Issue by pevik** [acerv/runltp-ng#16]
I'd prefer to have a bit more in test output. E.g. instead of:

```
# runltp-ng -r net.nfs
...
Starting suite: net.nfs
nfs3_01: skip | tained
nfs3t_01: pass | tained
...
```

have test *duration* (printed user friendly - results.json contains non-user friendly: e.g. `0.20882654190063477`):
```
nfs3_01: skip | tained (20s)
nfs3t_01: pass | tained (1min 30s)
```

or test *duration* and test *command line*:
```
nfs3_01: skip | tained duration: 20s, cmd: nfs01.sh -v 3 -t udp
nfs3t_01: pass | tained duration: 1min 30s, cmd: nfs01.sh -v 3 -t tcp
```

Although some tests have quite long cmdline, thus maybe have it on separate line. e.g: `net_stress.ipsec_icmp`:
```
icmp6-uni-basic08 icmp-uni-basic.sh -6 -A rfc4106_128 -p esp_aead -m transport -s 10:100:1000:10000:65490
```
thus ok, if you add it just to verbose mode (https://github.com/acerv/runltp-ng/issues/18).

**Comment by acerv** [comment]
Fixed by https://github.com/acerv/runltp-ng/commit/9b1f054a44b76224f29832b5f59c3e43e642987f
