### ISSUE TITLE
SSH protocol missing ability to tweak it

### ISSUE THREAD

**Issue by asmorodskyi** [acerv/runltp-ng#8]
Exactly needed support for two keys : 
1. UserKnownHostsFile=/dev/null 
2. StrictHostKeyChecking=no

**Comment by acerv** [comment]
Implemented by https://github.com/acerv/runltp-ng/commit/dffc14517881f1defc28adcd719d4e2ba24e8379 . Please @asmorodskyi  let me know if feature is working properly.

**Comment by acerv** [comment]
Working https://openqa.suse.de/tests/9605397#step/accept01/1
